/*
 * 游乐场构建脚本：web/apps/*.jlc → 自包含沙箱页 + 注册表 + 浏览器可用的经典脚本运行时。
 * Copyright (c) 2026 JLC contributors. MIT licensed.
 *
 *   node scripts/build-web.mjs          生成 web/ 下的产物
 *   node scripts/build-web.mjs --check  只比对，有漂移就退出码 1（npm run check 用）
 *
 * 产物：
 *   web/jlc-runtime.js  仅运行时（无编译器），app 页面用它装载 .jbc
 *   web/jlc-full.js     运行时 + 编译器 + 门面，控制台页面用它现场编译
 *   web/apps/<名>.html   自包含沙箱页（内联 base64 .jbc，零网络请求，可 file:// 直开）
 *   web/registry.js     元数据 + 接口清单 + 各策略档的拒绝预告（全局脚本，同样避开 CORS）
 *
 * 设计约束：游乐场必须能在 GitHub Pages（静态托管）与 file:// 下工作，
 * 因此不使用 ES module import（opaque origin 下会被 CORS 拦），改成拼接成经典脚本。
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  ABI_VERSION,
  BYTECODE_VERSION,
  VERSION,
  checkPermissions,
  encodeModule,
  loadModule,
  resolvePolicy,
} from "../jlc-vm.js";
import { compileAst } from "../jlc-compiler.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const WEB = join(ROOT, "web");
const APPS = join(WEB, "apps");
const PROFILES = ["strict", "open", "trusted"];
const CHECK = process.argv.includes("--check");

/* ------------------------------------------------------------------ */
/* 工具                                                               */
/* ------------------------------------------------------------------ */

const out = [];
function emit(absolute, text) {
  const name = relative(ROOT, absolute);
  const previous = (() => {
    try {
      return readFileSync(absolute, "utf8");
    } catch {
      return null;
    }
  })();
  if (previous === text) return;
  if (CHECK) {
    out.push(name);
    return;
  }
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, text);
  out.push(name);
}

/** 把 ES module 源码剥成可在 IIFE 里跑的经典脚本源码。 */
function deModule(source, name) {
  if (/<\/script/i.test(source)) throw new Error(`${name}: 源码里出现 </script，无法内联到 HTML`);
  if (/\bimport\.meta\b/.test(source)) throw new Error(`${name}: 使用了 import.meta，无法拼成经典脚本`);
  if (/^\s*(?:for\s+)?await\b/m.test(source)) throw new Error(`${name}: 顶层 await 无法拼成经典脚本`);
  return source
    .replace(/^\uFEFF/, "")
    .replace(/^import\s*\{[\s\S]*?\}\s*from\s*["'][^"']+["'];?[ \t]*$/gm, "")
    .replace(/^import\s*["'][^"']+["'];?[ \t]*$/gm, "")
    .replace(/^export\s+default\s+[A-Za-z_$][\w$]*;?[ \t]*$/gm, "")
    .replace(/^export\s*\{[^}]*\}\s*(?:from\s*["'][^"']+["'])?\s*;?[ \t]*$/gm, "")
    .replace(/^export\s+(?=(?:const|let|var|async\s+function|function|class)\b)/gm, "");
}

function topLevelNames(source) {
  const found = new Set();
  const pattern = /^(?:const|let|var)\s+([A-Za-z_$][\w$]*)|^(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)|^class\s+([A-Za-z_$][\w$]*)/gm;
  for (const match of source.matchAll(pattern)) found.add(match[1] ?? match[2] ?? match[3]);
  return found;
}

function bundle(parts, tail, banner) {
  const stripped = parts.map((part) => deModule(part.source, part.name));
  const seen = new Map();
  stripped.forEach((source, index) => {
    for (const name of topLevelNames(source)) {
      if (seen.has(name)) {
        throw new Error(`拼接冲突：${name} 同时出现在 ${parts[seen.get(name)].name} 与 ${parts[index].name} 的顶层`);
      }
      seen.set(name, index);
    }
  });
  return `/* GENERATED by scripts/build-web.mjs — 不要手改，改源码后跑 npm run build:web */\n/* ${banner} */\n(function (global) {\n"use strict";\n\n${stripped.join("\n\n")}\n\n${tail}\n})(typeof globalThis !== "undefined" ? globalThis : this);\n`;
}

function base64(bytes) {
  return Buffer.from(bytes).toString("base64");
}

function sha256(text) {
  return createHash("sha256").update(text).digest("hex").slice(0, 16);
}

/* ------------------------------------------------------------------ */
/* 应用页元数据                                                        */
/* ------------------------------------------------------------------ */

function readMeta(source, name) {
  const block = /^\/\*\*?\s*@jlc-page([\s\S]*?)\*\//.exec(source);
  const meta = { name, title: name, summary: "", policy: "open", isolation: "soft", fault: "degrade", capabilities: [], demo: "" };
  if (!block) return meta;
  for (const line of block[1].split("\n")) {
    const match = /^\s*\*\s*([A-Za-z-]+)\s*:([^*]*)$/.exec(line);
    if (!match) continue;
    const key = match[1].trim();
    const value = match[2].trim();
    if (key === "capabilities") meta.capabilities = value ? value.split(/[,\s]+/).filter(Boolean) : [];
    else if (key in meta) meta[key] = value;
  }
  return meta;
}

/** 编译期检查：声明档下必须挂得住（manifest 模式给出聚合预检清单）。 */
function buildApp(source, name, policy) {
  const { module } = compileAst(source, { sourceName: `web/apps/${name}.jlc`, policy, policyMode: "manifest" });
  const bytes = encodeModule(module);
  const reload = loadModule(bytes, { sourceName: `${name}.jbc` });
  const requirements = module.requirements ?? [];
  const sites = requirements.reduce((total, item) => total + (item.sites?.length ?? 0), 0);
  if ((reload.requirements ?? []).length !== requirements.length) throw new Error(`${name}: .jbc 往返后接口清单不一致`);
  const denialsByProfile = {};
  for (const profile of PROFILES) {
    const resolved = resolvePolicy(profile);
    denialsByProfile[profile] = checkPermissions(requirements, resolved).map((denied) => ({
      key: denied.key,
      kind: denied.kind,
      detail: denied.detail,
      reason: denied.reason,
      sites: (denied.sites ?? []).slice(0, 3),
    }));
  }
  return {
    module,
    requirements,
    reload,
    bytes,
    denialsByProfile,
  };
}

/* ------------------------------------------------------------------ */
/* 页面模板                                                           */
/* ------------------------------------------------------------------ */

function pageDocument(meta, jbc) {
  const data = [
    `data-target="#mount"`,
    `data-policy="${meta.policy}"`,
    `data-fault="${meta.fault}"`,
    `data-isolation="${meta.isolation}"`,
    `data-app="${meta.name}"`,
    (meta.capabilities ?? []).length ? `data-capabilities="${meta.capabilities.join(" ")}"` : "",
  ].filter(Boolean).join(" ");
  return `<!doctype html>
<!-- GENERATED by scripts/build-web.mjs — 源文件 web/apps/${meta.name}.jlc，改源码后跑 npm run build:web -->
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta name="referrer" content="no-referrer">
<title>JLC 0.3 · ${meta.title}</title>
<link rel="stylesheet" href="../playground.css">
</head>
<body class="app-page" data-app="${meta.name}">
<header class="app-bar">
  <a class="app-back" href="../index.html">← 控制台</a>
  <span class="app-title">${meta.title}</span>
  <span class="app-meta" data-role="meta">装载中…</span>
  <span class="app-spacer"></span>
  <button type="button" data-role="reload" title="按当前参数重新装载">重新装载</button>
  <button type="button" data-role="probe" title="在沙箱内部试探宿主资源">隔离自检</button>
</header>
<p class="app-summary">${meta.summary}</p>
<main id="mount" class="app-mount"></main>
<section class="app-audit" data-role="audit" hidden>
  <h2>被策略收回的接口</h2>
  <ul data-role="denied-list"></ul>
</section>
<footer class="app-foot">
  <p class="app-demo">${meta.demo}</p>
  <p class="muted">本页零网络依赖：字节码内联在下面的 <code>script[type="text/jbc"]</code> 里，运行时是 <code>../jlc-runtime.js</code>（不含编译器）。查询串 <code>?policy=&amp;fault=&amp;isolation=</code> 可覆盖策略。</p>
</footer>
<script id="jlc-module" type="text/jbc" ${data}>
${base64(jbc)}
</script>
<script src="../jlc-runtime.js"></script>
<script src="../app-page.js"></script>
</body>
</html>
`;
}

/* ------------------------------------------------------------------ */
/* 主流程                                                             */
/* ------------------------------------------------------------------ */

function main() {
  const runtimeSource = readFileSync(join(ROOT, "jlc-vm.js"), "utf8");
  const compilerSource = readFileSync(join(ROOT, "jlc-compiler.js"), "utf8");
  const facadeSource = readFileSync(join(ROOT, "jlc.js"), "utf8");

  const runtimeExports = [
    "VERSION", "ABI_VERSION", "BYTECODE_VERSION",
    "createVMKernel", "VMKernel", "JLCVM", "JLCProgram",
    "loadModule", "encodeModule", "decodeModule", "verifyModule", "auditModule", "disassembleModule",
    "resolvePolicy", "checkPermissions", "policyViolation", "scopeStylesheet",
    "SECURITY_PROFILES", "SYSCALLS",
    "HARD_BLOCKED_TAGS", "HARD_BLOCKED_PROPERTIES", "BLOCKED_TAGS", "URL_ATTRIBUTES",
    "JLCRuntimeError", "JLCVerifyError", "JLCPolicyError", "JLCQuotaError", "JLCIsolationError",
  ];
  emit(
    join(WEB, "jlc-runtime.js"),
    bundle(
      [{ name: "jlc-vm.js", source: runtimeSource }],
      `global.JLCRuntime = Object.freeze({\n${runtimeExports.map((name) => `  ${name},`).join("\n")}\n});`,
      `JLC 运行时（仅 VM，无编译器）· v${VERSION} · abi ${ABI_VERSION} · bytecode ${BYTECODE_VERSION}`,
    ),
  );

  const fullExports = [
    ...runtimeExports.filter((name) => !["JLCVM", "VMKernel"].includes(name)),
    "JLCCompileError", "tokenize", "Parser", "optimizeProgram", "compileAst", "CompilerKernel",
    "JLCKernel", "createKernel", "JLC",
  ];
  emit(
    join(WEB, "jlc-full.js"),
    bundle(
      [
        { name: "jlc-vm.js", source: runtimeSource },
        { name: "jlc-compiler.js", source: compilerSource },
        { name: "jlc.js", source: facadeSource },
      ],
      `global.JLCFull = Object.freeze({\n${fullExports.map((name) => `  ${name},`).join("\n")}\n});`,
      `JLC 全量门面（编译器 + VM）· v${VERSION}`,
    ),
  );

  const apps = readdirSync(APPS)
    .filter((file) => file.endsWith(".jlc"))
    .sort()
    .map((file) => file.slice(0, -4));
  const registry = [];

  for (const name of apps) {
    const source = readFileSync(join(APPS, `${name}.jlc`), "utf8");
    const meta = readMeta(source, name);
    if (!PROFILES.includes(meta.policy)) throw new Error(`${name}: 未知策略档 ${meta.policy}`);
    let built;
    try {
      built = buildApp(source, name, meta.policy);
    } catch (error) {
      throw new Error(`${name}: 按 ${meta.policy} 档预检失败\n${error.message}`);
    }
    const { module, requirements, bytes, denialsByProfile, sites } = built;
    emit(join(APPS, `${name}.html`), pageDocument(meta, bytes));
    registry.push({
      name,
      title: meta.title,
      summary: meta.summary,
      demo: meta.demo,
      policy: meta.policy,
      fault: meta.fault,
      isolation: meta.isolation,
      capabilities: meta.capabilities,
      href: `./apps/${name}.html`,
      source: `./apps/${name}.jlc`,
      bytes: bytes.length,
      hash: sha256(source),
      app: module.app,
      functions: module.functions.length,
      pool: module.pool.length,
      sites,
      requirements: requirements.map((item) => ({
        kind: item.kind,
        detail: item.detail,
        key: `${item.kind}:${item.detail}`,
        sites: (item.sites ?? []).slice(0, 3),
      })),
      denialsByProfile,
    });
  }

  const registryText = `/* GENERATED by scripts/build-web.mjs — 不要手改 */\n/* JLC 游乐场注册表 · v${VERSION} · ${registry.length} 个应用 */\n(function (global) {\n"use strict";\nglobal.JLC_REGISTRY = Object.freeze(${JSON.stringify({
    version: VERSION,
    abi: ABI_VERSION,
    bytecode: BYTECODE_VERSION,
    profiles: PROFILES.map((name) => ({ name, policy: publicPolicy(resolvePolicy(name)) })),
    apps: registry,
  }, null, 2)});\n})(typeof globalThis !== "undefined" ? globalThis : this);\n`;
  emit(join(WEB, "registry.js"), registryText);

  console.log(`${CHECK ? "漂移" : "生成"} ${out.length} 个文件${out.length ? `:\n  ${out.join("\n  ")}` : ""}`);
  if (CHECK && out.length) {
    console.error("产物与源码不同步：请运行 npm run build:web");
    process.exitCode = 1;
  }
}

function publicPolicy(policy) {
  const keep = [
    "profile", "label", "fingerprint", "urlSchemes", "allowDataUrls", "allowBlobUrls", "allowCustomElements", "allowEventAttributes",
    "allowSandboxedFrames", "allowHtmlInjection", "allowNetwork", "allowWindowEvents", "strictUrls",
    "frameSandbox", "frameMinIntervalMs", "htmlMaxChars", "maxDomNodes", "maxStyleBytes", "styleScoping",
  ];
  const result = {};
  for (const key of keep) {
    const value = policy[key];
    if (typeof value === "object" && value !== null && "size" in value) result[key] = [...value];
    else if (value !== undefined) result[key] = value;
  }
  return result;
}

main();
