/* GENERATED by scripts/build-web.mjs — 不要手改 */
/* JLC 游乐场注册表 · v0.3.0 · 5 个应用 */
(function (global) {
"use strict";
global.JLC_REGISTRY = Object.freeze({
  "version": "0.3.0",
  "abi": "jlc-abi/2",
  "bytecode": 2,
  "profiles": [
    {
      "name": "strict",
      "policy": {
        "profile": "strict",
        "label": "严格档 · 与 0.2 行为等价",
        "fingerprint": "0x1abb6752",
        "urlSchemes": [
          "about:",
          "http:",
          "https:",
          "mailto:",
          "tel:",
          "sms:",
          "ftp:",
          "geo:"
        ],
        "allowDataUrls": false,
        "allowBlobUrls": false,
        "allowCustomElements": false,
        "allowEventAttributes": false,
        "allowSandboxedFrames": false,
        "allowHtmlInjection": false,
        "allowNetwork": true,
        "allowWindowEvents": false,
        "strictUrls": false,
        "frameSandbox": "",
        "frameMinIntervalMs": 16,
        "htmlMaxChars": 0,
        "maxDomNodes": 4000,
        "maxStyleBytes": 65536,
        "styleScoping": "off"
      }
    },
    {
      "name": "open",
      "policy": {
        "profile": "open",
        "label": "开放档 · 更像真实浏览器，但每个特权都带内核加固",
        "fingerprint": "0xdc8f9df4",
        "urlSchemes": [
          "about:",
          "http:",
          "https:",
          "mailto:",
          "tel:",
          "sms:",
          "ftp:",
          "geo:",
          "blob:",
          "data:",
          "srcdoc:",
          "magnet:"
        ],
        "allowDataUrls": true,
        "allowBlobUrls": true,
        "allowCustomElements": true,
        "allowEventAttributes": false,
        "allowSandboxedFrames": true,
        "allowHtmlInjection": true,
        "allowNetwork": true,
        "allowWindowEvents": true,
        "strictUrls": false,
        "frameSandbox": "allow-scripts allow-forms allow-popups",
        "frameMinIntervalMs": 4,
        "htmlMaxChars": 262144,
        "maxDomNodes": 20000,
        "maxStyleBytes": 131072,
        "styleScoping": "prefix"
      }
    },
    {
      "name": "trusted",
      "policy": {
        "profile": "trusted",
        "label": "受信档 · 第一方字节码：放开界面，仍禁 innerHTML 与脚本 URL",
        "fingerprint": "0xcde6e2a7",
        "urlSchemes": [
          "about:",
          "http:",
          "https:",
          "mailto:",
          "tel:",
          "sms:",
          "ftp:",
          "geo:",
          "blob:",
          "data:",
          "srcdoc:",
          "magnet:"
        ],
        "allowDataUrls": true,
        "allowBlobUrls": true,
        "allowCustomElements": true,
        "allowEventAttributes": false,
        "allowSandboxedFrames": true,
        "allowHtmlInjection": true,
        "allowNetwork": true,
        "allowWindowEvents": true,
        "strictUrls": false,
        "frameSandbox": "allow-scripts allow-forms allow-popups allow-modals allow-same-origin",
        "frameMinIntervalMs": 0,
        "htmlMaxChars": 2097152,
        "maxDomNodes": 60000,
        "maxStyleBytes": 524288,
        "styleScoping": "off"
      }
    }
  ],
  "apps": [
    {
      "name": "html-preview",
      "title": "富文本预览（iframe + srcdoc）",
      "summary": "不可信 HTML 的官方去处：srcdoc + 内核托管 sandbox；strict 下 frame 被整体收回",
      "demo": "左边输入 HTML，右边在 frame 里渲染（150ms 防抖）。把 fault 切到 stop 看预检失败清单；切到 strict 看 frame 被收回后应用如何降级",
      "policy": "open",
      "fault": "degrade",
      "isolation": "strict",
      "capabilities": [
        "clipboard"
      ],
      "href": "./apps/html-preview.html",
      "source": "./apps/html-preview.jlc",
      "bytes": 3321,
      "hash": "8cfffd2af3257aea",
      "app": "HtmlPreview",
      "functions": 32,
      "pool": 76,
      "requirements": [
        {
          "kind": "frame",
          "detail": "iframe",
          "key": "frame:iframe",
          "sites": [
            "view@136"
          ]
        },
        {
          "kind": "frame",
          "detail": "srcdoc",
          "key": "frame:srcdoc",
          "sites": [
            "view@139"
          ]
        },
        {
          "kind": "host",
          "detail": "timer",
          "key": "host:timer",
          "sites": [
            "action:stage@20"
          ]
        },
        {
          "kind": "tag",
          "detail": "button",
          "key": "tag:button",
          "sites": [
            "view@89",
            "view@102"
          ]
        },
        {
          "kind": "tag",
          "detail": "div",
          "key": "tag:div",
          "sites": [
            "view@8",
            "view@16",
            "view@81"
          ]
        },
        {
          "kind": "tag",
          "detail": "main",
          "key": "tag:main",
          "sites": [
            "view@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "p",
          "key": "tag:p",
          "sites": [
            "view@123"
          ]
        },
        {
          "kind": "tag",
          "detail": "span",
          "key": "tag:span",
          "sites": [
            "when:yes@0",
            "when:yes@0",
            "view@31"
          ]
        },
        {
          "kind": "tag",
          "detail": "strong",
          "key": "tag:strong",
          "sites": [
            "view@24"
          ]
        },
        {
          "kind": "tag",
          "detail": "textarea",
          "key": "tag:textarea",
          "sites": [
            "view@51"
          ]
        }
      ],
      "denialsByProfile": {
        "strict": [
          {
            "key": "frame:iframe",
            "kind": "frame",
            "detail": "iframe",
            "reason": "allowSandboxedFrames = false",
            "sites": [
              "view@136"
            ]
          },
          {
            "key": "frame:srcdoc",
            "kind": "frame",
            "detail": "srcdoc",
            "reason": "allowSandboxedFrames = false",
            "sites": [
              "view@139"
            ]
          }
        ],
        "open": [],
        "trusted": []
      }
    },
    {
      "name": "json-browser",
      "title": "JSON 浏览器（resource + data: 端点）",
      "summary": "resource 的“装载/reload 才请求”语义；端点是 data: URL，离线可跑，同时演示 url:data 的策略门",
      "demo": "重新载入只发一次请求；loading / error / 成功由 resource 快照驱动。strict 档仍然授予 host:http（清单里没有 url:data——端点是派生值，静态判不出），但写入时的 sanitizer 会把 data: URL 中和掉：看右上角 neutralized 计数与 error 徽章",
      "policy": "open",
      "fault": "degrade",
      "isolation": "soft",
      "capabilities": [],
      "href": "./apps/json-browser.html",
      "source": "./apps/json-browser.jlc",
      "bytes": 4064,
      "hash": "fb61401a774846ee",
      "app": "JsonBrowser",
      "functions": 38,
      "pool": 86,
      "requirements": [
        {
          "kind": "host",
          "detail": "http",
          "key": "host:http",
          "sites": [
            "resource:docs@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "button",
          "key": "tag:button",
          "sites": [
            "view@37"
          ]
        },
        {
          "kind": "tag",
          "detail": "div",
          "key": "tag:div",
          "sites": [
            "view@8",
            "view@29",
            "view@96"
          ]
        },
        {
          "kind": "tag",
          "detail": "input",
          "key": "tag:input",
          "sites": [
            "view@50"
          ]
        },
        {
          "kind": "tag",
          "detail": "main",
          "key": "tag:main",
          "sites": [
            "view@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "p",
          "key": "tag:p",
          "sites": [
            "view@168"
          ]
        },
        {
          "kind": "tag",
          "detail": "pre",
          "key": "tag:pre",
          "sites": [
            "view@155"
          ]
        },
        {
          "kind": "tag",
          "detail": "span",
          "key": "tag:span",
          "sites": [
            "when:yes@0",
            "when:yes@0",
            "when:yes@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "table",
          "key": "tag:table",
          "sites": [
            "view@104"
          ]
        },
        {
          "kind": "tag",
          "detail": "tbody",
          "key": "tag:tbody",
          "sites": [
            "view@134"
          ]
        },
        {
          "kind": "tag",
          "detail": "td",
          "key": "tag:td",
          "sites": [
            "each:body@21",
            "each:empty@3"
          ]
        },
        {
          "kind": "tag",
          "detail": "th",
          "key": "tag:th",
          "sites": [
            "each:body@14",
            "view@118",
            "view@125"
          ]
        },
        {
          "kind": "tag",
          "detail": "thead",
          "key": "tag:thead",
          "sites": [
            "view@112"
          ]
        },
        {
          "kind": "tag",
          "detail": "tr",
          "key": "tag:tr",
          "sites": [
            "each:body@0",
            "each:empty@0",
            "view@115"
          ]
        }
      ],
      "denialsByProfile": {
        "strict": [],
        "open": [],
        "trusted": []
      }
    },
    {
      "name": "palette",
      "title": "样式作用域 + 数据 URL",
      "summary": "style 被前缀限定到本实例；data: 图片在 strict 下被中和成 about:blank，在 open 下照常显示",
      "demo": "滑块只改插值进 style 的变量，style 会被前缀限定在本实例；切到 strict 后那张 data: 图片会被 sanitizer 换成 about:blank（url: 类接口不参与装载拒绝，除非 strictUrls），看右上角 neutralized 计数",
      "policy": "open",
      "fault": "degrade",
      "isolation": "soft",
      "capabilities": [],
      "href": "./apps/palette.html",
      "source": "./apps/palette.jlc",
      "bytes": 3086,
      "hash": "5f8f7f113f6f462a",
      "app": "PaletteLab",
      "functions": 25,
      "pool": 71,
      "requirements": [
        {
          "kind": "tag",
          "detail": "button",
          "key": "tag:button",
          "sites": [
            "view@153",
            "view@166"
          ]
        },
        {
          "kind": "tag",
          "detail": "code",
          "key": "tag:code",
          "sites": [
            "view@146"
          ]
        },
        {
          "kind": "tag",
          "detail": "div",
          "key": "tag:div",
          "sites": [
            "view@8",
            "view@21"
          ]
        },
        {
          "kind": "tag",
          "detail": "i",
          "key": "tag:i",
          "sites": [
            "view@16"
          ]
        },
        {
          "kind": "tag",
          "detail": "img",
          "key": "tag:img",
          "sites": [
            "view@192"
          ]
        },
        {
          "kind": "tag",
          "detail": "input",
          "key": "tag:input",
          "sites": [
            "view@36",
            "view@72",
            "view@108"
          ]
        },
        {
          "kind": "tag",
          "detail": "main",
          "key": "tag:main",
          "sites": [
            "view@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "p",
          "key": "tag:p",
          "sites": [
            "view@138",
            "view@221"
          ]
        },
        {
          "kind": "tag",
          "detail": "span",
          "key": "tag:span",
          "sites": [
            "view@29",
            "view@65",
            "view@101"
          ]
        },
        {
          "kind": "url",
          "detail": "data:",
          "key": "url:data:",
          "sites": [
            "view@200"
          ]
        }
      ],
      "denialsByProfile": {
        "strict": [],
        "open": [],
        "trusted": []
      }
    },
    {
      "name": "todo",
      "title": "待办清单",
      "summary": "state / derive / each key / 不可变重建的最小样本，只用内核内建函数",
      "demo": "新增、勾选、删除都只重跑受影响的那一行；列表节点靠 key 复用，不会整表重建",
      "policy": "strict",
      "fault": "degrade",
      "isolation": "soft",
      "capabilities": [],
      "href": "./apps/todo.html",
      "source": "./apps/todo.jlc",
      "bytes": 2838,
      "hash": "82cefe793e9dc8a0",
      "app": "TodoLab",
      "functions": 28,
      "pool": 80,
      "requirements": [
        {
          "kind": "tag",
          "detail": "button",
          "key": "tag:button",
          "sites": [
            "each:body@45",
            "view@48"
          ]
        },
        {
          "kind": "tag",
          "detail": "form",
          "key": "tag:form",
          "sites": [
            "view@15"
          ]
        },
        {
          "kind": "tag",
          "detail": "h2",
          "key": "tag:h2",
          "sites": [
            "view@8"
          ]
        },
        {
          "kind": "tag",
          "detail": "input",
          "key": "tag:input",
          "sites": [
            "each:body@13",
            "view@29"
          ]
        },
        {
          "kind": "tag",
          "detail": "li",
          "key": "tag:li",
          "sites": [
            "each:body@0",
            "each:empty@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "main",
          "key": "tag:main",
          "sites": [
            "view@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "p",
          "key": "tag:p",
          "sites": [
            "view@86"
          ]
        },
        {
          "kind": "tag",
          "detail": "span",
          "key": "tag:span",
          "sites": [
            "each:body@38"
          ]
        },
        {
          "kind": "tag",
          "detail": "ul",
          "key": "tag:ul",
          "sites": [
            "view@61"
          ]
        }
      ],
      "denialsByProfile": {
        "strict": [],
        "open": [],
        "trusted": []
      }
    },
    {
      "name": "tracer",
      "title": "响应式追踪器",
      "summary": "定时器 / emit / 窗口事件委托 / capability 计数——把 runtime.ledger() 的数字变成会动的东西",
      "demo": "起停定时器看 cycles/effects 变化；「广播」用 emit 在根元素上自顶向下捕获；把 fault 切到 report 再看窗口事件被拒时的行为差异",
      "policy": "open",
      "fault": "degrade",
      "isolation": "strict",
      "capabilities": [
        "storage"
      ],
      "href": "./apps/tracer.html",
      "source": "./apps/tracer.jlc",
      "bytes": 3663,
      "hash": "178fd3a5b0930aa8",
      "app": "SignalTracer",
      "functions": 48,
      "pool": 91,
      "requirements": [
        {
          "kind": "host",
          "detail": "emit",
          "key": "host:emit",
          "sites": [
            "action:broadcast@0"
          ]
        },
        {
          "kind": "host",
          "detail": "timer",
          "key": "host:timer",
          "sites": [
            "action:start@22"
          ]
        },
        {
          "kind": "tag",
          "detail": "button",
          "key": "tag:button",
          "sites": [
            "view@48",
            "view@61",
            "view@74"
          ]
        },
        {
          "kind": "tag",
          "detail": "div",
          "key": "tag:div",
          "sites": [
            "view@14",
            "view@101",
            "view@109"
          ]
        },
        {
          "kind": "tag",
          "detail": "main",
          "key": "tag:main",
          "sites": [
            "view@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "p",
          "key": "tag:p",
          "sites": [
            "view@245"
          ]
        },
        {
          "kind": "tag",
          "detail": "span",
          "key": "tag:span",
          "sites": [
            "when:yes@0",
            "each:body@0",
            "each:empty@0"
          ]
        },
        {
          "kind": "tag",
          "detail": "strong",
          "key": "tag:strong",
          "sites": [
            "view@22",
            "view@117",
            "view@140"
          ]
        },
        {
          "kind": "window",
          "detail": "event",
          "key": "window:event",
          "sites": [
            "view@235"
          ]
        }
      ],
      "denialsByProfile": {
        "strict": [
          {
            "key": "window:event",
            "kind": "window",
            "detail": "event",
            "reason": "allowWindowEvents = false",
            "sites": [
              "view@235"
            ]
          }
        ],
        "open": [],
        "trusted": []
      }
    }
  ]
});
})(typeof globalThis !== "undefined" ? globalThis : this);
